export const ROUTES = {
    HOME: "/",
    TRENDS: "/trends",
    TASKS: "/tasks",
    TICKETS: "/tickets",
    PAYMENTS: "/payments",
    CLIENT: "/client",
    LIST: "/client/list",
    REVIEWS: "/client/reviews",
    NOTIFICATIONS: "/client/notifications",
    INVENTORY: "/inventory",
    PRODUCTS: "/inventory/products",
    ORDERS: "/inventory/orders",
    SUPPLIERS: "/inventory/suppliers",
    SHOP: "/shop",
    REPORTS: "/reports",
    TENDER: "/tender",
    SETTINGS: "/settings",
    KNOWLEDGE: "/knowledge",
};
